Feature/gap
jaredh159/tailwind-react-native-classnames pull request #212
Opened 2023-01-13 17:26 UTC by rborn

2023-01-13 17:32 UTC, rborn commented
for #205 , not sure why the previous PR is not there 🧐

2023-01-13 18:20 UTC, jaredh159 requested changes
this looks great, just the one proposed change to tighten up the call site.

thanks for the contribution, again. 👍

2023-01-13 18:20 UTC, jaredh159 commented on src/ClassParser.ts
> +      );
we can simplify this to just: 

```suggestion
      style = gap(this.rest, this.context, theme?.gap);
```

2023-01-13 18:23 UTC, jaredh159 commented on src/ClassParser.ts
> +      );
@rborn oh, and can you rebase? it looks like you've got some old commits in there. if you add  an upstream remote, you should be able to run `git pull --rebase upstream master` and eliminate those.

2023-01-16 09:50 UTC, rborn commented
@jaredh159 ok, fixed `theme?.gap` and maybe some merge conflicts?  The diff looks clean, maybe we can merge ?

2023-01-17 19:33 UTC, jaredh159 commented
@rborn code diff looks good, but i'm a bit of a stickler about keeping my commit history tidy, and you've got duplicated commits, and commits from previous PR's in your history, so i'd rather not merge all of that in. do you know how to clean that up with a rebase? if not, can you maybe add me as a collaborator on your fork, and i'll rebase it and then i can merge?

2023-01-18 09:35 UTC, rborn commented
@jaredh159 yeah, I managed somehow to do a total mess out of this 😅 Now it should be clean, sorry for this

2023-01-18 14:43 UTC, merged